# Chinese (Simplified, China) translations for ceilometer.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
# aji.zqfan <aji.zqfan@gmail.com>, 2015
# yelu <yelu@unitedstack.com>, 2013
# Tom Fifield <tom@openstack.org>, 2013
# 颜海峰 <yanheven@gmail.com>, 2014
# Yu Zhang, 2013
msgid ""
msgstr ""
"Project-Id-Version:  Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-18 06:10+0000\n"
"PO-Revision-Date: 2015-03-18 03:44+0000\n"
"Last-Translator: aji.zqfan <aji.zqfan@gmail.com>\n"
"Language-Team: Chinese (China) "
"(http://www.transifex.com/projects/p/ceilometer/language/zh_CN/)\n"
"Plural-Forms: nplurals=1; plural=0\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/collector.py:123
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr "UDP: 无法解码由 %s 发送的数据"

#: ceilometer/collector.py:126
#, python-format
msgid "UDP: Storing %s"
msgstr "UDP: 正在存储%s"

#: ceilometer/collector.py:130
msgid "UDP: Unable to store meter"
msgstr "UDP: 无法存储计量器"

#: ceilometer/notification.py:163 ceilometer/notifier.py:46
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr "无法为%s加载任何通知处理器"

#: ceilometer/notification.py:179
#, python-format
msgid "Event types from %(name)s: %(type)s (ack_on_error=%(error)s)"
msgstr ""

#: ceilometer/notification.py:213
#, python-format
msgid "Pipeline endpoint: %s"
msgstr " 流水线入口：%s"

#: ceilometer/notifier.py:37
#, python-format
msgid "loading notification handlers from %s"
msgstr "从%s加载通知处理器"

#: ceilometer/pipeline.py:312
#, python-format
msgid "Unable to load publisher %s"
msgstr "无法加载发布器%s"

#: ceilometer/pipeline.py:330
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr "流水线%(pipeline)s：使用参数%(param)s初始化变形器实例%(name)s"

#: ceilometer/pipeline.py:349 ceilometer/pipeline.py:413
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr "流水线%(pipeline)s：发布器%(pub)s报错，继续执行"

#: ceilometer/pipeline.py:368
#, python-format
msgid "Pipeline %(pipeline)s: Sample dropped by transformer %(trans)s"
msgstr "流水线%(pipeline)s：数据点被变形器%(trans)s丢弃"

#: ceilometer/pipeline.py:376
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr "流水线%(pipeline)s：数据%(smp)s的变形器%(trans)s遇到错误，退出"

#: ceilometer/pipeline.py:399
#, python-format
msgid "Pipeline %(pipeline)s: Transform sample %(smp)s from %(trans)s transformer"
msgstr "流水线%(pipeline)s：使用变形器%(trans)s作用于数据%(smp)s "

#: ceilometer/pipeline.py:429
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr "流水线%(pipeline)s：变形器%(trans)s清空数据时出错"

#: ceilometer/pipeline.py:625
msgid "detected decoupled pipeline config format"
msgstr "检测到分离的流水线配置格式"

#: ceilometer/pipeline.py:646
msgid "detected deprecated pipeline config format"
msgstr "检测到废弃的流水线配置格式"

#: ceilometer/pipeline.py:670
#, python-format
msgid "Pipeline config file: %s"
msgstr "流水线配置文件：%s"

#: ceilometer/pipeline.py:676
#, python-format
msgid "Pipeline config: %s"
msgstr "流水线配置：%s"

#: ceilometer/service.py:103
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr "工作线程%(worker_name)s的数量%(workers)s非法，必须大于0"

#: ceilometer/agent/base.py:130
#, python-format
msgid "Polling pollster %(poll)s in the context of %(src)s"
msgstr "在上下文环境%(src)s执行采集器%(poll)s"

#: ceilometer/agent/base.py:161
#, python-format
msgid ""
"Found following duplicated resoures for %(name)s in context of "
"%(source)s:%(list)s. Check pipeline configuration."
msgstr ""

#: ceilometer/agent/base.py:172
#, python-format
msgid "Skip polling pollster %s, no resources found"
msgstr "没有任何资源被发现，跳过采集器%s"

#: ceilometer/agent/base.py:184
#, python-format
msgid "Prevent pollster %(name)s for polling source %(source)s anymore!"
msgstr ""

#: ceilometer/agent/base.py:190
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr "遇到错误%(name)s：%(error)s，继续执行"

#: ceilometer/agent/base.py:244
#, python-format
msgid "Skip loading extension for %s"
msgstr "跳过为%s加载扩展"

#: ceilometer/agent/base.py:248
#, python-format
msgid "Failed to import extension for %(name)s: %(error)s"
msgstr "无法为%(name)s引入扩展：%(error)s"

#: ceilometer/agent/base.py:357
#, python-format
msgid "Unable to discover resources: %s"
msgstr "无法发现资源：%s"

#: ceilometer/agent/base.py:359
#, python-format
msgid "Unknown discovery extension: %s"
msgstr "未知的发现器插件：%s"

#: ceilometer/agent/plugin_base.py:72
#, python-format
msgid "Skip due to keystone error %s"
msgstr "跳过执行，因为keystone出错了：%s，"

#: ceilometer/agent/plugin_base.py:79
#, python-format
msgid "Skipping because %s service is not registered in keystone"
msgstr "跳过执行，因为%s服务没有在keystone中注册"

#: ceilometer/agent/plugin_base.py:118
msgid ""
"get_exchange_topics API of NotificationPlugin isdeprecated, implements "
"get_targets instead."
msgstr ""

#: ceilometer/alarm/rpc.py:56
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr "告警%(alarm_id)s没有为状态从%(previous)s变迁到%(state)s配置动作，忽略收到的通知。"

#: ceilometer/alarm/service.py:94
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr "在 %d 个警报上初始化评估周期"

#: ceilometer/alarm/service.py:99
msgid "alarm evaluation cycle failed"
msgstr "警报周期评估失败"

#: ceilometer/alarm/service.py:104
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr "跳过警报 %s：不支持的类型"

#: ceilometer/alarm/service.py:108
#, python-format
msgid "evaluating alarm %s"
msgstr "评估警报 %s"

#: ceilometer/alarm/service.py:112
#, python-format
msgid "Failed to evaluate alarm %s"
msgstr "评估告警%s时失败了"

#: ceilometer/alarm/service.py:252
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr "无法为警报 %(alarm_id)s 解析动作 %(action)s "

#: ceilometer/alarm/service.py:261
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr "警报 %(alarm_id)s 的动作 %(scheme)s 未知，无法通知"

#: ceilometer/alarm/service.py:267
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr "使用动作%(act)s通知告警%(id)s"

#: ceilometer/alarm/service.py:272
#, python-format
msgid "Unable to notify alarm %s"
msgstr "无法通知警报 %s"

#: ceilometer/alarm/service.py:293
msgid "Unable to notify for an alarm with no action"
msgstr "无法为一个没有动作的警报进行通知"

#: ceilometer/alarm/evaluator/__init__.py:75
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr "因为 %(reason)s, 警报 %(id)s 转换至 %(state)s "

#: ceilometer/alarm/evaluator/__init__.py:87
msgid "alarm state update failed"
msgstr "警报状态更新失败"

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr "获取警报失败"

#: ceilometer/alarm/evaluator/combination.py:52
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr "告警%(alarm_ids)s处于未知的状态"

#: ceilometer/alarm/evaluator/combination.py:74
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr "迁移到状态%(state)s，因为告警%(alarm_ids)s处于状态%(state)s"

#: ceilometer/alarm/evaluator/combination.py:78
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr "停留在状态%(state)s因为告警%(alarm_ids)s处于状态%(state)s"

#: ceilometer/alarm/evaluator/combination.py:99
#: ceilometer/alarm/evaluator/gnocchi.py:207
#: ceilometer/alarm/evaluator/threshold.py:178
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr "尝试评估告警%s，但是该告警当前不在激活的时间范围内"

#: ceilometer/alarm/evaluator/gnocchi.py:99
#: ceilometer/alarm/evaluator/threshold.py:89
#, python-format
msgid "stats query %s"
msgstr "统计信息查询 %s"

#: ceilometer/alarm/evaluator/gnocchi.py:103
#: ceilometer/alarm/evaluator/threshold.py:95
msgid "alarm stats retrieval failed"
msgstr "警报统计信息获取失败"

#: ceilometer/alarm/evaluator/gnocchi.py:106
#, python-format
msgid "alarm stats retrieval failed: %s"
msgstr "告警状态检索失败：%s"

#: ceilometer/alarm/evaluator/gnocchi.py:121
#: ceilometer/alarm/evaluator/threshold.py:56
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr "查询 %(start)s 到 %(now)s 之间的统计信息"

#: ceilometer/alarm/evaluator/gnocchi.py:133
#: ceilometer/alarm/evaluator/threshold.py:112
#, python-format
msgid "%d datapoints are unknown"
msgstr "%d 数据点为未知"

#: ceilometer/alarm/evaluator/gnocchi.py:156
#: ceilometer/alarm/evaluator/threshold.py:137
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr "有%(count)d个数据满足%(disposition)s阈值，因而状态迁移到%(state)s，最近的一次数据：%(most_recent)s"

#: ceilometer/alarm/evaluator/gnocchi.py:160
#: ceilometer/alarm/evaluator/threshold.py:141
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr "有%(count)d个数据满足%(disposition)s阈值，因而状态保持为%(state)s，最近的一次数据：%(most_recent)s"

#: ceilometer/alarm/evaluator/gnocchi.py:219
#: ceilometer/alarm/evaluator/threshold.py:197
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr "将值 %(value)s 与阈值 %(limit)s 相比较"

#: ceilometer/alarm/evaluator/threshold.py:66
#, python-format
msgid "sanitize stats %s"
msgstr "审查统计信息 %s"

#: ceilometer/alarm/evaluator/threshold.py:75
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr "排除%s个弱相关的数据"

#: ceilometer/alarm/evaluator/threshold.py:84
#, python-format
msgid "pruned statistics to %d"
msgstr "裁剪统计信息到%d个"

#: ceilometer/alarm/notifier/log.py:30
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s of %(severity)s priority from"
" %(previous)s to %(current)s with action %(action)s because %(reason)s."
msgstr ""

#: ceilometer/alarm/notifier/rest.py:64
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s from %(previous)s to "
"%(current)s with action %(action)s because %(reason)s. request-id: "
"%(request_id)s "
msgstr ""
"正在通知告警%(alarm_name)s "
"%(alarm_id)s从状态%(previous)s变为%(current)s，动作为%(action)s，原因为%(reason)s。请求编号：%(request_id)s"

#: ceilometer/alarm/partition/coordination.py:132
#, python-format
msgid "triggering %s"
msgstr "正在触发 %s"

#: ceilometer/alarm/partition/coordination.py:133
#, python-format
msgid "known evaluators %s"
msgstr "已知的评估器%s"

#: ceilometer/alarm/partition/coordination.py:136
#, python-format
msgid "per evaluator allocation %s"
msgstr "每个评估器分配得到%s"

#: ceilometer/alarm/partition/coordination.py:146
#, python-format
msgid ""
"%(this)s bailing on distribution cycle as older partition detected: "
"%(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:152
#, python-format
msgid "%(verb)s-ing %(alloc)s to %(eval)s"
msgstr "正在%(verb)s %(alloc)s 到%(eval)s"

#: ceilometer/alarm/partition/coordination.py:156
#, python-format
msgid "master taking %s for self"
msgstr "主节点为自己取得%s"

#: ceilometer/alarm/partition/coordination.py:174
#, python-format
msgid "newly deleted alarms %s"
msgstr "新删除的警报%s"

#: ceilometer/alarm/partition/coordination.py:177
msgid "alarm deletion activity requires rebalance"
msgstr "警报删除活动需要重新均衡"

#: ceilometer/alarm/partition/coordination.py:202
#, python-format
msgid "%s still warming up"
msgstr "%s仍在准备中"

#: ceilometer/alarm/partition/coordination.py:207
#, python-format
msgid "last heard from %(report)s %(delta)s seconds ago"
msgstr "最后一次从%(report)s得到消息是在%(delta)s秒前"

#: ceilometer/alarm/partition/coordination.py:212
#, python-format
msgid "%(this)s detects stale evaluator: %(stale)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:217
#, python-format
msgid "%(this)s sees older potential master: %(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:219
#, python-format
msgid "%(this)s is master?: %(is_master)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:232
#, python-format
msgid "newly created alarms %s"
msgstr "新创建的警报%s"

#: ceilometer/alarm/partition/coordination.py:243
#, python-format
msgid "%(this)s not overtaken as master? %(still_ahead)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:253
#, python-format
msgid "%s checking mastership status"
msgstr "%s正在检查主节点状态"

#: ceilometer/alarm/partition/coordination.py:260
msgid "mastership check failed"
msgstr "主节点检查失败"

#: ceilometer/alarm/partition/coordination.py:270
#, python-format
msgid "%(this)s knows about %(reports)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:276
#, python-format
msgid "%(this)s got assignment: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:283
#, python-format
msgid "%(this)s got allocation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:289
#, python-format
msgid "%s reporting presence"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:293
msgid "presence reporting failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:298
#, python-format
msgid "%s has no assigned alarms to evaluate"
msgstr "%s没有被指派告警以供评估"

#: ceilometer/alarm/partition/coordination.py:302
#, python-format
msgid "%(this)s alarms for evaluation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:308
msgid "assignment retrieval failed"
msgstr "获取失败"

#: ceilometer/alarm/storage/impl_hbase.py:86
#: ceilometer/event/storage/impl_hbase.py:79
#: ceilometer/storage/impl_hbase.py:131
msgid "Dropping HBase schema..."
msgstr "正在丢弃HBase的schema"

#: ceilometer/alarm/storage/impl_hbase.py:93
#: ceilometer/event/storage/impl_hbase.py:85
#: ceilometer/storage/impl_hbase.py:138
msgid "Cannot disable table but ignoring error"
msgstr "无法禁用表，但是忽略该错误"

#: ceilometer/alarm/storage/impl_hbase.py:97
#: ceilometer/event/storage/impl_hbase.py:89
#: ceilometer/storage/impl_hbase.py:142
msgid "Cannot delete table but ignoring error"
msgstr "无法删除表，但是忽略该错误"

#: ceilometer/alarm/storage/models.py:70
msgid "timestamp should be datetime object"
msgstr "timestamp必须是datatime对象"

#: ceilometer/alarm/storage/models.py:72
msgid "state_timestamp should be datetime object"
msgstr "state_timestamp必须是datetime对象"

#: ceilometer/api/app.py:136
#, python-format
msgid "Starting server in PID %s"
msgstr "正在启动服务进程PID %s"

#: ceilometer/api/app.py:137
msgid "Configuration:"
msgstr "配置"

#: ceilometer/api/app.py:141
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr "服务在0.0.0.0:%(sport)s上运行，可以通过http://127.0.0.1:%(vport)s来查看"

#: ceilometer/api/app.py:145
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr "在 http://%(host)s:%(port)s上服务"

#: ceilometer/api/middleware.py:105
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr "解析HTTP响应失败: %s"

#: ceilometer/api/controllers/v2/alarms.py:84
#, python-format
msgid "Alarm quota exceeded for user %(u)s on project %(p)s"
msgstr "用户%(u)s在项目%(p)s中的告警配额已溢出"

#: ceilometer/api/controllers/v2/alarms.py:166
#, python-format
msgid "Timezone %s is not valid"
msgstr "时区%s不合法"

#: ceilometer/api/controllers/v2/alarms.py:281
msgid "Time constraint names must be unique for a given alarm."
msgstr "一个指定的告警的时间约束名称必须唯一"

#: ceilometer/api/controllers/v2/alarms.py:291
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr "类型为%(type)s的告警必须设置%(rule)s"

#: ceilometer/api/controllers/v2/alarms.py:302
#, python-format
msgid "%(rule1)s and %(rule2)s cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:319
#, python-format
msgid "Unable to parse action %s"
msgstr "无法解析动作%s"

#: ceilometer/api/controllers/v2/alarms.py:322
#, python-format
msgid "Unsupported action %s"
msgstr "动作%s不支持"

#: ceilometer/api/controllers/v2/alarms.py:509
#, python-format
msgid "Alarm with name=%s exists"
msgstr "名称为%s的告警已存在"

#: ceilometer/api/controllers/v2/alarms.py:519
#, python-format
msgid "Error while putting alarm: %s"
msgstr "修改告警%s时遇到错误"

#: ceilometer/api/controllers/v2/alarms.py:520
#: ceilometer/api/controllers/v2/alarms.py:688
msgid "Alarm incorrect"
msgstr "警报不正确"

#: ceilometer/api/controllers/v2/alarms.py:580
msgid "state invalid"
msgstr "状态无效"

#: ceilometer/api/controllers/v2/alarms.py:681
#, python-format
msgid "Alarm with name='%s' exists"
msgstr "名称为'%s'的告警已经存在"

#: ceilometer/api/controllers/v2/alarms.py:687
#, python-format
msgid "Error while posting alarm: %s"
msgstr "创建告警%s时遇到错误"

#: ceilometer/api/controllers/v2/base.py:50
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr "无法找到%(entity)s %(id)s "

#: ceilometer/api/controllers/v2/base.py:59
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:220
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:225
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:230
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:240
#, python-format
msgid "Alarm %s not found"
msgstr "告警%s没有找到"

#: ceilometer/api/controllers/v2/base.py:242
#, python-format
msgid "Alarm %(alarm_id)s not found in project %(project)s"
msgstr "告警%(alarm_id)s在项目%(project)s中未找到"

#: ceilometer/api/controllers/v2/events.py:172
msgid "operator {} is incorrect"
msgstr "操作符{}不合法"

#: ceilometer/api/controllers/v2/events.py:195
#, python-format
msgid "Getting traits for %s"
msgstr "正在为%s获取特征"

#: ceilometer/api/controllers/v2/events.py:266
msgid "Event"
msgstr "事件"

#: ceilometer/api/controllers/v2/events.py:269
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr "从数据库返回了多个id为%s的事件"

#: ceilometer/api/controllers/v2/meters.py:181
msgid "clamping min timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:186
msgid "clamping max timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:286
#: ceilometer/api/controllers/v2/samples.py:126
msgid "Limit must be positive"
msgstr "limit必须是正数"

#: ceilometer/api/controllers/v2/meters.py:376
msgid "Period must be positive."
msgstr "period 参数必须是正数"

#: ceilometer/api/controllers/v2/meters.py:398
#, python-format
msgid "computed value coming from %r"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:408
#, python-format
msgid "Invalid period %(period)s: %(err)s"
msgstr "非法的间隔%(period)s: %(err)s"

#: ceilometer/api/controllers/v2/query.py:204
#, python-format
msgid "Filter expression not valid: %s"
msgstr "过滤表达式不合法：%s"

#: ceilometer/api/controllers/v2/query.py:219
#, python-format
msgid "Order-by expression not valid: %s"
msgstr "orderby表达式不合法：%s"

#: ceilometer/api/controllers/v2/query.py:229
msgid "Limit should be positive"
msgstr "limit必须是正整数"

#: ceilometer/api/controllers/v2/query.py:323
#, python-format
msgid "String %s is not a valid isotime"
msgstr "字符串%s不是个合法的标准时间格式"

#: ceilometer/api/controllers/v2/query.py:324
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr "解析时间戳%s失败"

#: ceilometer/api/controllers/v2/resources.py:127
msgid "Resource"
msgstr "资源"

#: ceilometer/api/controllers/v2/samples.py:145
msgid "Sample"
msgstr "数据"

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:39
#, python-format
msgid "Combined state of alarms %s"
msgstr "将告警%s的状态进行组合"

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:48
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr "告警组合规则必须包含至少两个不同的告警id"

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:69
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr "无法在组合规则中指定告警%s自身"

#: ceilometer/api/controllers/v2/alarm_rules/threshold.py:93
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/cmd/storage.py:39
msgid "Clearing expired metering data"
msgstr "正在清除过期的监控数据"

#: ceilometer/cmd/storage.py:44
msgid "Nothing to clean, database metering time to live is disabled"
msgstr "监控数据库过期时间未激活，没有数据要清除"

#: ceilometer/cmd/storage.py:48
msgid "Clearing expired event data"
msgstr "正在清除过期的事件数据"

#: ceilometer/cmd/storage.py:53
msgid "Nothing to clean, database event time to live is disabled"
msgstr "事件数据库过期时间未激活，没有数据要清除"

#: ceilometer/compute/notifications/cpu.py:50
#, python-format
msgid "An error occurred while building %(m)s sample: %(e)s"
msgstr "构造指标%(m)s的数据时遇到错误：%(e)s"

#: ceilometer/compute/pollsters/cpu.py:31
#, python-format
msgid "checking instance %s"
msgstr "正在检查虚拟机%s"

#: ceilometer/compute/pollsters/cpu.py:34
#, python-format
msgid "CPUTIME USAGE: %(instance)s %(time)d"
msgstr "虚拟机%(instance)s的CPU时间为%(time)d"

#: ceilometer/compute/pollsters/cpu.py:48
#: ceilometer/compute/pollsters/cpu.py:79
#: ceilometer/compute/pollsters/disk.py:131
#: ceilometer/compute/pollsters/disk.py:341
#: ceilometer/compute/pollsters/disk.py:523
#: ceilometer/compute/pollsters/disk.py:604
#: ceilometer/compute/pollsters/disk.py:699
#: ceilometer/compute/pollsters/memory.py:47
#: ceilometer/compute/pollsters/memory.py:90
#: ceilometer/compute/pollsters/net.py:106
#, python-format
msgid "Exception while getting samples %s"
msgstr "在获取监控数据时遇到异常：%s"

#: ceilometer/compute/pollsters/cpu.py:51
#, python-format
msgid "Obtaining CPU time is not implemented for %s"
msgstr "为%s获取CPU时间尚未实现"

#: ceilometer/compute/pollsters/cpu.py:54
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr "无法为虚拟机%(id)s获取CPU时间：%(e)s"

#: ceilometer/compute/pollsters/cpu.py:63
#, python-format
msgid "Checking CPU util for instance %s"
msgstr "为虚拟机%s查询CPU使用率"

#: ceilometer/compute/pollsters/cpu.py:67
#, python-format
msgid "CPU UTIL: %(instance)s %(util)d"
msgstr "虚拟机%(instance)s的CPU使用率为%(util)d"

#: ceilometer/compute/pollsters/cpu.py:82
#, python-format
msgid "Obtaining CPU Util is not implemented for %s"
msgstr "为%s获取CPU使用率尚未实现"

#: ceilometer/compute/pollsters/cpu.py:85
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr "无法为虚拟机%(id)s获取CPU使用率：%(e)s"

#: ceilometer/compute/pollsters/disk.py:139
#: ceilometer/compute/pollsters/disk.py:344
#: ceilometer/compute/pollsters/disk.py:526
#: ceilometer/compute/pollsters/disk.py:707
#: ceilometer/compute/pollsters/net.py:114
#, python-format
msgid "%(inspector)s does not provide data for  %(pollster)s"
msgstr "探测器%(inspector)s没有为%(pollster)s提供数据"

#: ceilometer/compute/pollsters/disk.py:144
#: ceilometer/compute/pollsters/disk.py:350
#: ceilometer/compute/pollsters/disk.py:532
#: ceilometer/compute/pollsters/disk.py:613
#: ceilometer/compute/pollsters/net.py:119
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr "忽略虚拟机%(name)s：%(error)s"

#: ceilometer/compute/pollsters/disk.py:607
#, python-format
msgid "%(inspector)s does not provide data for %(pollster)s"
msgstr "%(inspector)s无法为采集器%(pollster)s提供数据"

#: ceilometer/compute/pollsters/disk.py:713
#, python-format
msgid "Ignoring instance %(name)s (%(instance_id)s) : %(error)s"
msgstr "忽略虚拟机%(name)s (%(instance_id)s) : %(error)s"

#: ceilometer/compute/pollsters/memory.py:31
#, python-format
msgid "Checking memory usage for instance %s"
msgstr "为虚拟机%s检查内存使用信息"

#: ceilometer/compute/pollsters/memory.py:35
#, python-format
msgid "MEMORY USAGE: %(instance)s %(usage)f"
msgstr "虚拟机%(instance)s的内存使用为%(usage)f"

#: ceilometer/compute/pollsters/memory.py:60
#, python-format
msgid "Obtaining Memory Usage is not implemented for %s"
msgstr "获取内存使用信息尚未在%s中实现"

#: ceilometer/compute/pollsters/memory.py:63
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr "无法为%(id)s获取内存使用信息：%(e)s"

#: ceilometer/compute/pollsters/memory.py:73
#, python-format
msgid "Checking resident memory for instance %s"
msgstr "正在检查虚拟机%s的常驻内存RSS"

#: ceilometer/compute/pollsters/memory.py:78
#, python-format
msgid "RESIDENT MEMORY: %(instance)s %(resident)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:103
#, python-format
msgid "Obtaining Resident Memory is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/net.py:92
#, python-format
msgid "checking net info for instance %s"
msgstr "为虚拟机%s检查网络信息"

#: ceilometer/compute/virt/inspector.py:290
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr "无法加载管理程序的探测器：%s"

#: ceilometer/compute/virt/hyperv/utilsv2.py:223
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr "在Hyper-V上找不到 VM %s"

#: ceilometer/compute/virt/hyperv/utilsv2.py:225
#, python-format
msgid "Duplicate VM name found: %s"
msgstr "找到重复 VM 名称：%s"

#: ceilometer/compute/virt/libvirt/inspector.py:54
msgid "Connection to libvirt broken"
msgstr "无法连接到libvirt"

#: ceilometer/compute/virt/libvirt/inspector.py:79
#, python-format
msgid "Connecting to libvirt: %s"
msgstr "正在连接 libvirt：%s"

#: ceilometer/compute/virt/libvirt/inspector.py:97
#, python-format
msgid ""
"Error from libvirt while looking up instance <name=%(name)s, id=%(id)s>: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:117
#, python-format
msgid ""
"Failed to inspect data of instance <name=%(name)s, id=%(id)s>, domain "
"state is SHUTOFF."
msgstr "为虚拟机<name=%(name)s, id=%(id)s>获取监控数据失败了，虚拟机状态为SHUTOFF"

#: ceilometer/compute/virt/libvirt/inspector.py:187
#, python-format
msgid ""
"Failed to inspect memory usage of instance <name=%(name)s, id=%(id)s>, "
"can not get info from libvirt."
msgstr "为虚拟机<name=%(name)s, id=%(id)s>采集内存使用指标失败了，无法从libvirt获取信息。"

#: ceilometer/compute/virt/libvirt/inspector.py:195
#, python-format
msgid ""
"Failed to inspect memory usage of %(instance_uuid)s, can not get info "
"from libvirt: %(error)s"
msgstr "为虚拟机%(instance_uuid)s采集内存使用指标失败了，无法从libvirt获取信息：%(error)s"

#: ceilometer/compute/virt/vmware/inspector.py:94
#: ceilometer/compute/virt/vmware/inspector.py:111
#: ceilometer/compute/virt/vmware/inspector.py:143
#: ceilometer/compute/virt/vmware/inspector.py:156
#, python-format
msgid "VM %s not found in VMware Vsphere"
msgstr "无法在VMware Vsphere中找到虚拟机%s"

#: ceilometer/compute/virt/xenapi/inspector.py:57
msgid "XenAPI not installed"
msgstr "XenAPI没有安装"

#: ceilometer/compute/virt/xenapi/inspector.py:63
msgid "Must specify connection_url, and connection_password to use"
msgstr "使用时必须指定connection_url和connection_password"

#: ceilometer/compute/virt/xenapi/inspector.py:66
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr "无法登录到XenAPI(Dom0磁盘是空么？)"

#: ceilometer/compute/virt/xenapi/inspector.py:73
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr "无法连接到XenAPI：%s"

#: ceilometer/compute/virt/xenapi/inspector.py:96
#, python-format
msgid "VM %s not found in XenServer"
msgstr "无法在XenServer中找到虚拟机%s"

#: ceilometer/compute/virt/xenapi/inspector.py:99
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr "多个虚拟机%s在XenServer中被找到"

#: ceilometer/compute/virt/xenapi/inspector.py:112
#, python-format
msgid "Could not get VM %s CPU Utilization"
msgstr "无法获取虚拟机%s的CPU使用率"

#: ceilometer/dispatcher/__init__.py:41
#, python-format
msgid "loading dispatchers from %s"
msgstr "正在从%s加载分发器"

#: ceilometer/dispatcher/__init__.py:49
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr "无法为%s加载任何分发器"

#: ceilometer/dispatcher/database.py:48
#, python-format
msgid "Failed to connect to db, purpose %(purpose)s re-try later: %(err)s"
msgstr "无法连接到数据库，目的%(purpose)s稍后重试：%(err)s"

#: ceilometer/dispatcher/database.py:73 ceilometer/dispatcher/http.py:80
#, python-format
msgid ""
"metering data %(counter_name)s for %(resource_id)s @ %(timestamp)s: "
"%(counter_volume)s"
msgstr "再时间点%(timestamp)s为资源%(resource_id)s获得指标%(counter_name)s的监控数据：%(counter_volume)s"

#: ceilometer/dispatcher/database.py:91 ceilometer/dispatcher/http.py:108
#, python-format
msgid "Failed to record metering data: %s"
msgstr "无法保存监控数据：%s"

#: ceilometer/dispatcher/database.py:94 ceilometer/dispatcher/http.py:111
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr "消息签名不合法，丢弃消息：%r"

#: ceilometer/dispatcher/http.py:70
msgid ""
"Dispatcher target was not set, no meter will be posted. Set the target in"
" the ceilometer.conf file"
msgstr "分发器目标未设置，没有指标将被发送。在ceilometer.conf文件中设置目标。"

#: ceilometer/dispatcher/http.py:105
#, python-format
msgid "Message posting finished with status code %d."
msgstr "消息发送结束，状态码为%d"

#: ceilometer/energy/kwapi.py:88
msgid "Kwapi endpoint not found"
msgstr "Kwapi端点无法找到"

#: ceilometer/event/converter.py:78
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr "特征%s指定了插件但是没有提供插件的名称"

#: ceilometer/event/converter.py:87
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr "特征%(trait)s缺少可用的名为%(plugin)s的插件"

#: ceilometer/event/converter.py:97
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr "在特征定义中的必填项没有填写：'%s'"

#: ceilometer/event/converter.py:112
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:118
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr "特征%(trait)s包含了不合法的特征类型'%(type)s' "

#: ceilometer/event/converter.py:171
#, python-format
msgid "Required field %s not specified"
msgstr "必填项%s没有填写"

#: ceilometer/event/converter.py:348
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr "正在丢弃通知%(type)s (uuid:%(msgid)s)"

#: ceilometer/event/converter.py:372
#, python-format
msgid "Event Definitions configuration file: %s"
msgstr "事件定义配置文件：%s"

#: ceilometer/event/converter.py:382
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr "事件定义文件%(file)s中有非法YAML语法，行：%(line)s，列%(column)s。"

#: ceilometer/event/converter.py:388
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr "读取事件定义文件%(file)s时遇到YAML错误"

#: ceilometer/event/converter.py:395
msgid "No Event Definitions configuration file found! Using default config."
msgstr "没有找到事件定义配置文件！使用默认的配置。"

#: ceilometer/event/converter.py:399
#, python-format
msgid "Event Definitions: %s"
msgstr "事件定义：%s"

#: ceilometer/event/endpoint.py:34
msgid "Loading event definitions"
msgstr "正在加载事件定义"

#: ceilometer/event/storage/impl_hbase.py:124
#: ceilometer/event/storage/impl_sqlalchemy.py:209
#: ceilometer/event/storage/impl_sqlalchemy.py:213
#: ceilometer/event/storage/pymongo_base.py:76
#, python-format
msgid "Failed to record event: %s"
msgstr "无法记录事件：%s"

#: ceilometer/event/storage/impl_sqlalchemy.py:205
#: ceilometer/event/storage/pymongo_base.py:72
#, python-format
msgid "Failed to record duplicated event: %s"
msgstr "无法记录重复的事件：%s"

#: ceilometer/hardware/discovery.py:74
#, python-format
msgid "Couldn't obtain IP address of instance %s"
msgstr "无法为实例%s获取IP地址"

#: ceilometer/hardware/plugin.py:67
msgid "Passed resource dict must contain keys resource_id and resource_url."
msgstr "传入的资源字典必须包含键resource_id和resource_url"

#: ceilometer/hardware/plugin.py:109
#, python-format
msgid "inspector call failed for %(ident)s host %(host)s: %(err)s"
msgstr ""

#: ceilometer/hardware/plugin.py:140
#, python-format
msgid "Can NOT load inspector %(name)s: %(err)s"
msgstr "无法加载探测器%(name)s: %(err)s"

#: ceilometer/ipmi/platform/intel_node_manager.py:297
msgid "Node Manager init failed"
msgstr "节点管理器初始化失败"

#: ceilometer/ipmi/platform/ipmi_sensor.py:101
msgid "Wrong sensor type"
msgstr "错误的传感器类型"

#: ceilometer/ipmi/platform/ipmitool.py:39
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr "解析IPMI传感器数据失败，未知的传感器类型"

#: ceilometer/ipmi/platform/ipmitool.py:80
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr "解析IPMI传感器数据失败，从给定的输入中无法检索到数据"

#: ceilometer/ipmi/platform/ipmitool.py:102
msgid "ipmitool output length mismatch"
msgstr "ipmi输出长度不匹配"

#: ceilometer/ipmi/platform/ipmitool.py:128
msgid "running ipmitool failure"
msgstr "运行ipmitool时失败了"

#: ceilometer/ipmi/pollsters/node.py:66
#, python-format
msgid "Polling %(name)s faild for %(cnt)s times!"
msgstr "拉取%(name)s失败了%(cnt)s次！"

#: ceilometer/ipmi/pollsters/node.py:71 ceilometer/ipmi/pollsters/sensor.py:74
#, python-format
msgid "Pollster for %s is disabled!"
msgstr "%s的采集器被禁用"

#: ceilometer/ipmi/pollsters/sensor.py:68
#, python-format
msgid "Polling %(mtr)s sensor failed for %(cnt)s times!"
msgstr "拉取%(mtr)s传感器失败了%(cnt)s次！"

#: ceilometer/network/floatingip.py:54
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr "浮动IP使用情况：%s"

#: ceilometer/network/notifications.py:75
#, python-format
msgid "network notification %r"
msgstr "收到网络通知%r"

#: ceilometer/network/services/fwaas.py:47
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr "从fw %(id)s收到未知的状态%(stat)s，跳过该采样数据"

#: ceilometer/network/services/lbaas.py:62
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr "从pool %(id)s收到未知的状态%(stat)s，跳过该采样数据"

#: ceilometer/network/services/lbaas.py:110
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr "从vip %(id)s收到未知的状态%(stat)s，跳过该采样数据"

#: ceilometer/network/services/lbaas.py:151
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s,skipping sample"
msgstr "从member %(id)s收到未知的状态%(stat)s，跳过该采样数据"

#: ceilometer/network/services/lbaas.py:256
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr "忽略pool %(pool_id)s：%(error)s"

#: ceilometer/network/services/vpnaas.py:48
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s,skipping sample"
msgstr "从VPN%(id)s收到未知的状态%(stat)s，跳过该采样数据"

#: ceilometer/network/statistics/opencontrail/client.py:58
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr "Opencontrail接口返回状态%(status)s，原因%(reason)s"

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/network/statistics/opendaylight/test_client.py:142
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr "OpenDaylight接口返回状态%(status)s，原因%(reason)s"

#: ceilometer/network/statistics/opendaylight/driver.py:168
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr "请求无法连接到OpenDaylight的北向REST接口"

#: ceilometer/objectstore/rgw.py:80
msgid "Radosgw endpoint not found"
msgstr "Radosgw服务入口未找到"

#: ceilometer/objectstore/rgw_client.py:48
#, python-format
msgid "RGW AdminOps API returned %(status)s %(reason)s"
msgstr "RGW AdminOps接口返回%(status)s %(reason)s"

#: ceilometer/objectstore/swift.py:76
msgid "Swift endpoint not found"
msgstr "Swift端点无法找到"

#: ceilometer/openstack/common/log.py:298
#: ceilometer/openstack/common/versionutils.py:232
#, python-format
msgid "Deprecated: %s"
msgstr "建议不要使用：%s"

#: ceilometer/openstack/common/log.py:406
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "日志配置加载错误 %(log_config)s: %(err_msg)s"

#: ceilometer/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "系统日志工具必须是下列其中一项：%s"

#: ceilometer/openstack/common/log.py:715
#: ceilometer/openstack/common/versionutils.py:250
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "对建议不要使用的配置进行了后果极严重的调用：%(msg)s"

#: ceilometer/openstack/common/versionutils.py:99
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: ceilometer/openstack/common/versionutils.py:103
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: ceilometer/openstack/common/versionutils.py:107
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: ceilometer/openstack/common/versionutils.py:110
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr "文件发布器必须设置文件路径"

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr "max_bytes和backup_count必须是整数。"

#: ceilometer/publisher/messaging.py:88
#, python-format
msgid "Publishing policy set to %s"
msgstr "设置发布策略为%s"

#: ceilometer/publisher/messaging.py:90
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr "未知的发布策略(%s)，强制使用默认策略"

#: ceilometer/publisher/messaging.py:143
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr "发布的数据量超过本地队列最大长度，正在丢弃最老的%d个数据"

#: ceilometer/publisher/messaging.py:154
#, python-format
msgid "Failed to publish %d datapoints, queue them"
msgstr "发布%d个数据点时失败，将其入队"

#: ceilometer/publisher/messaging.py:158
#, python-format
msgid "Failed to publish %d datapoints, dropping them"
msgstr "发布%d个数据点时失败，正在将其丢弃"

#: ceilometer/publisher/udp.py:56
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr "通过UDP发布采样 %(msg)s 至 %(host)s:%(port)d"

#: ceilometer/publisher/udp.py:63
msgid "Unable to send sample over UDP"
msgstr "无法通过UDP发送采样"

#: ceilometer/storage/__init__.py:126
#, python-format
msgid "looking for %(name)r driver in %(namespace)r"
msgstr "正在名字空间%(namespace)r查找驱动%(name)r "

#: ceilometer/storage/impl_hbase.py:216 ceilometer/storage/impl_hbase.py:267
#, python-format
msgid "Query Resource table: %s"
msgstr "查询资源表：%s"

#: ceilometer/storage/impl_hbase.py:260
msgid "Pagination not implemented"
msgstr "未实现分页操作"

#: ceilometer/storage/impl_hbase.py:307
#, python-format
msgid "Query Meter Table: %s"
msgstr "查询指标表：%s"

#: ceilometer/storage/impl_log.py:40
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr "为资源%(resource_id)s获得指标%(counter_name)s的监控数据：%(counter_volume)s"

#: ceilometer/storage/impl_log.py:52
#, python-format
msgid "Dropping metering data with TTL %d"
msgstr "正在根据TTL %d丢弃监控数据"

#: ceilometer/storage/impl_mongodb.py:553
msgid ""
"Clearing expired metering data is based on native MongoDB time to live "
"feature and going in background."
msgstr "MongoDB正在后台使用原生的TTL机制清除过期监控数据。"

#: ceilometer/storage/impl_sqlalchemy.py:306
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr "未知的元数据类型。键(%s)将无法进行查询。"

#: ceilometer/storage/impl_sqlalchemy.py:359
#, python-format
msgid "%d samples removed from database"
msgstr "从数据库中移除%d个监控数据。"

#: ceilometer/storage/impl_sqlalchemy.py:378
msgid "Expired residual resource and meter definition data"
msgstr ""

#: ceilometer/storage/hbase/base.py:45
msgid "Creating a new in-memory HBase Connection object"
msgstr "正在创建一个新的内存HBase连接对象。"

#: ceilometer/storage/hbase/base.py:62
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr "正在连接%(host)s:%(port)s的HBase"

#: ceilometer/storage/hbase/inmemory.py:268
msgid "Opening in-memory HBase connection"
msgstr "正在打开内存HBase连接。"

#: ceilometer/storage/hbase/utils.py:474
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr "表%(table_name)s已经存在，无法创建。忽略此错误继续执行。"

#: ceilometer/storage/mongo/utils.py:246
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr "连接到%(nodelist)s节点的数据库%(db)s。"

#: ceilometer/storage/mongo/utils.py:264
#, python-format
msgid "Unable to connect to the database server: %(errmsg)s."
msgstr "无法连接到数据库服务器：%(errmsg)s。"

#: ceilometer/storage/mongo/utils.py:402
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb after %(retries)d retries. "
"Giving up."
msgstr "在%(retries)d次尝试后仍无法重连到MongoDB主节点。放弃重连。"

#: ceilometer/storage/mongo/utils.py:406
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr "无法重连到MongoDB主节点：%(errmsg)s。在%(retry_interval)d秒后进行重试。"

#: ceilometer/transformer/arithmetic.py:55
#, python-format
msgid "Arithmetic transformer must use at least one meter in expression '%s'"
msgstr "算术变形器在表达式'%s'中必须至少使用一个指标"

#: ceilometer/transformer/arithmetic.py:77
msgid "Expression evaluated to a NaN value!"
msgstr "表达式计算结果为NaN！"

#: ceilometer/transformer/arithmetic.py:93
#, python-format
msgid "Unable to evaluate expression %(expr)s: %(exc)s"
msgstr "无法计算表达式%(expr)s：%(exc)s"

#: ceilometer/transformer/arithmetic.py:107
#, python-format
msgid "Unable to perform calculation, not all of {%s} are present"
msgstr "并不是所有的{%s}都能获取到因而无法进行计算"

#: ceilometer/transformer/conversions.py:46
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr "扩缩变形器作用于来源：%(source)s，目标：%(target)s"

#: ceilometer/transformer/conversions.py:92
#: ceilometer/transformer/conversions.py:114
#, python-format
msgid "handling sample %s"
msgstr "正在处理数据%s"

#: ceilometer/transformer/conversions.py:95
#: ceilometer/transformer/conversions.py:135
#, python-format
msgid "converted to: %s"
msgstr "转换为: %s"

#: ceilometer/transformer/conversions.py:137
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr "因为之前没有数据（用来计算差值）因而丢弃数据：%s"

