# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-09 06:08+0000\n"
"PO-Revision-Date: 2014-09-02 00:36+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Chinese (China) (http://www.transifex.com/projects/p/"
"ceilometer/language/zh_CN/)\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ceilometer/collector.py:132
msgid "Dispatcher failed to handle the sample, requeue it."
msgstr ""

#: ceilometer/coordination.py:76
msgid "Error connecting to coordination backend."
msgstr ""

#: ceilometer/coordination.py:89
msgid "Error sending a heartbeat to coordination backend."
msgstr ""

#: ceilometer/coordination.py:142
msgid "Error getting group membership info from coordination backend."
msgstr ""

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "正在删除原始异常：%s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "意外的异常已发生 %d 次...正在重试。"

#: ceilometer/openstack/common/lockutils.py:117
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "未能释放所获取锁定“%s”"

#: ceilometer/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "在固定时段内循环调用"

#: ceilometer/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "在动态循环调用中"

#: ceilometer/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "未能理解规则 %s"

#: ceilometer/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "对于类型为 %s 的匹配项，不存在任何处理程序"

#: ceilometer/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "未能理解规则 %r "

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "在RPC清除期间发生异常。"

#: ceilometer/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "存在未处理的异常"
