# Translations template for ceilometer.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
# aji.zqfan <aji.zqfan@gmail.com>, 2015
# Shuwen SUN <chris-void@outlook.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-03-31 06:06+0000\n"
"PO-Revision-Date: 2015-03-21 13:37+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Chinese (China) (http://www.transifex.com/projects/p/"
"ceilometer/language/zh_CN/)\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ceilometer/collector.py:170
#, python-format
msgid "Dispatcher failed to handle the %s, requeue it."
msgstr "分发器处理%s失败，重新入队"

#: ceilometer/collector.py:212
#, python-format
msgid "Error processing event and it will be dropped: %s"
msgstr "处理事件%s时报错，将其丢弃"

#: ceilometer/coordination.py:79 ceilometer/coordination.py:91
msgid "Error connecting to coordination backend."
msgstr "无法连接到协调器后端"

#: ceilometer/coordination.py:107
msgid "Error sending a heartbeat to coordination backend."
msgstr "无法发送心跳信息到协调器后端"

#: ceilometer/coordination.py:177
msgid "Error getting group membership info from coordination backend."
msgstr "从协调器后端获取组成员信息时出错"

#: ceilometer/compute/pollsters/memory.py:106
#, python-format
msgid "Could not get Resident Memory Usage for %(id)s: %(e)s"
msgstr "无法为%(id)s获取常驻内存使用量RSS： %(e)s"

#: ceilometer/dispatcher/http.py:135
msgid "Status Code: %{code}s. Failed to dispatch event: %{event}s"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "在固定时段内循环调用"

#: ceilometer/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "在动态循环调用中"

#: ceilometer/openstack/common/service.py:268
msgid "Unhandled exception"
msgstr "存在未处理的异常"

#: ceilometer/publisher/kafka_broker.py:95
#: ceilometer/publisher/kafka_broker.py:177
#, python-format
msgid "Failed to connect to Kafka service: %s"
msgstr "无法连接到Kafka服务：%s"

#: ceilometer/publisher/kafka_broker.py:158
msgid "Failed to retry to send sample data with max_retry times"
msgstr "尝试发送数据达到最大重试次数后仍失败"

#: ceilometer/publisher/kafka_broker.py:198
#, python-format
msgid "Failed to send sample data: %s"
msgstr "发送指标数据失败：%s"
