# Translations template for ceilometer.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 5.0.0.0b4.dev128\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-09-23 14:39+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.0\n"

#: ceilometer/collector.py:135
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:142
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/notification.py:199
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/pipeline.py:396
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:415
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr ""

#: ceilometer/pipeline.py:434
#, python-format
msgid "Pipeline %(pipeline)s: %(status)s after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:464
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:501
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:517
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:712 ceilometer/pipeline.py:774
msgid "detected decoupled pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:798 ceilometer/pipeline.py:817
#, python-format
msgid "Pipeline config: %s"
msgstr ""

#: ceilometer/agent/manager.py:178
#, python-format
msgid "Skip pollster %(name)s, no %(p_context)sresources found this cycle"
msgstr ""

#: ceilometer/agent/manager.py:183
#, python-format
msgid "Polling pollster %(poll)s in the context of %(src)s"
msgstr ""

#: ceilometer/agent/manager.py:208
#, python-format
msgid "Prevent pollster %(name)s for polling source %(source)s anymore!"
msgstr ""

#: ceilometer/agent/manager.py:214
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/manager.py:290
#, python-format
msgid "Skip loading extension for %s"
msgstr ""

#: ceilometer/agent/manager.py:293
#, python-format
msgid "Failed to import extension for %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/manager.py:468
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent/manager.py:470
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/agent/manager.py:479
msgid "Error stopping pollster."
msgstr ""

#: ceilometer/alarm/service.py:94
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:99
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:111
#, python-format
msgid "Failed to evaluate alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:179
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:188
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:199
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:220
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:75
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:87
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:57
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:79
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:83
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:111
#: ceilometer/alarm/evaluator/threshold.py:95
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:114
#, python-format
msgid "alarm stats retrieval failed: %s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:141
#: ceilometer/alarm/evaluator/threshold.py:112
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:164
#: ceilometer/alarm/evaluator/threshold.py:137
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:168
#: ceilometer/alarm/evaluator/threshold.py:141
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/notifier/log.py:31
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s of %(severity)s priority from"
" %(previous)s to %(current)s with action %(action)s because %(reason)s."
msgstr ""

#: ceilometer/alarm/notifier/rest.py:68
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s with severity %(severity)s "
"from %(previous)s to %(current)s with action %(action)s because "
"%(reason)s. request-id: %(request_id)s "
msgstr ""

#: ceilometer/alarm/storage/models.py:70
msgid "timestamp should be datetime object"
msgstr ""

#: ceilometer/alarm/storage/models.py:72
msgid "state_timestamp should be datetime object"
msgstr ""

#: ceilometer/api/app.py:133
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: ceilometer/api/app.py:134
msgid "Configuration:"
msgstr ""

#: ceilometer/api/app.py:138
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: ceilometer/api/app.py:142
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: ceilometer/api/middleware.py:102
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:95
#, python-format
msgid "Alarm quota exceeded for user %(u)s on project %(p)s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:177
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:292
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:302
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:313
#, python-format
msgid "%(rule1)s and %(rule2)s cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:329
#, python-format
msgid "duplicate actions are found: %s, remove duplicate ones"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:335
#, python-format
msgid "%(name)s count exceeds maximum value %(maximum)d"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:346
#, python-format
msgid "Unable to parse action %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:349
#, python-format
msgid "Unsupported action %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:352
#, python-format
msgid "You are not authorized to create action: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:594
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:606
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:607
#: ceilometer/api/controllers/v2/alarms.py:772
msgid "Alarm incorrect"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:663
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:765
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:771
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:50
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:59
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:220
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:225
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:230
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:240
#, python-format
msgid "Alarm %s not found"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:242
#, python-format
msgid "Alarm %(alarm_id)s not found in project %(project)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:190
#, python-format
msgid ""
"operator %(operator)s is not supported. the supported operators are: "
"%(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:297
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:300
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:308
msgid "Samples should be included in request body"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:394
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:423
#, python-format
msgid "Invalid period %(period)s: %(err)s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:205
#, python-format
msgid "Filter expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:220
#, python-format
msgid "Order-by expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:318
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:319
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2/resources.py:128
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2/samples.py:144
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2/utils.py:50
msgid "Limit must be positive"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:39
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:48
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:69
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/threshold.py:93
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:56
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:87
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:144
#: ceilometer/compute/pollsters/disk.py:354
#: ceilometer/compute/pollsters/disk.py:540
#: ceilometer/compute/pollsters/disk.py:622
#: ceilometer/compute/pollsters/net.py:110
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:723
#, python-format
msgid "Ignoring instance %(name)s (%(instance_id)s) : %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:65
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:314
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:223
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:225
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:103
#, python-format
msgid ""
"Error from libvirt while looking up instance <name=%(name)s, id=%(id)s>: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:123
#, python-format
msgid ""
"Failed to inspect data of instance <name=%(name)s, id=%(id)s>, domain "
"state is SHUTOFF."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:193
#, python-format
msgid ""
"Failed to inspect memory usage of instance <name=%(name)s, id=%(id)s>, "
"can not get info from libvirt."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:201
#, python-format
msgid ""
"Failed to inspect memory usage of %(instance_uuid)s, can not get info "
"from libvirt: %(error)s"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:107
#: ceilometer/compute/virt/vmware/inspector.py:124
#: ceilometer/compute/virt/vmware/inspector.py:156
#: ceilometer/compute/virt/vmware/inspector.py:169
#, python-format
msgid "VM %s not found in VMware vSphere"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:57
msgid "XenAPI not installed"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:63
msgid "Must specify connection_url, and connection_password to use"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:66
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:74
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:97
#, python-format
msgid "VM %s not found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:100
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:113
#, python-format
msgid "Could not get VM %s CPU Utilization"
msgstr ""

#: ceilometer/dispatcher/__init__.py:51
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:57
msgid "The Yaml file that defines per metric archive policies."
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:61
msgid ""
"The Yaml file that defines mapping between samples and gnocchi "
"resources/metrics"
msgstr ""

#: ceilometer/dispatcher/gnocchi_client.py:123
#, python-format
msgid ""
"Fail to post measure on metric %(metric_name)s of resource "
"%(resource_id)s with status: %(status_code)d: %(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi_client.py:147
#, python-format
msgid ""
"Resource %(resource_id)s creation failed with status: %(status_code)d: "
"%(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi_client.py:167
#, python-format
msgid ""
"Resource %(resource_id)s update failed with status: %(status_code)d: "
"%(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi_client.py:191
#, python-format
msgid ""
"Fail to create metric %(metric_name)s of resource %(resource_id)s with "
"status: %(status_code)d: %(msg)s"
msgstr ""

#: ceilometer/dispatcher/http.py:82
msgid ""
"Dispatcher target was not set, no meter will be posted. Set the target in"
" the ceilometer.conf file"
msgstr ""

#: ceilometer/dispatcher/http.py:120
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/http.py:123
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/event/converter.py:80
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr ""

#: ceilometer/event/converter.py:89
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:99
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr ""

#: ceilometer/event/converter.py:114
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:120
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:179
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:356
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/event/converter.py:390
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr ""

#: ceilometer/event/converter.py:396
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr ""

#: ceilometer/event/converter.py:407
#, python-format
msgid "Event Definitions: %s"
msgstr ""

#: ceilometer/hardware/discovery.py:95
#, python-format
msgid "Couldn't obtain IP address of instance %s"
msgstr ""

#: ceilometer/ipmi/platform/intel_node_manager.py:300
msgid "Node Manager init failed"
msgstr ""

#: ceilometer/ipmi/platform/ipmi_sensor.py:101
msgid "Wrong sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:39
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:80
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:102
msgid "ipmitool output length mismatch"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:128
msgid "running ipmitool failure"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:66
#, python-format
msgid "Polling %(name)s faild for %(cnt)s times!"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:71 ceilometer/ipmi/pollsters/sensor.py:74
#, python-format
msgid "Pollster for %s is disabled!"
msgstr ""

#: ceilometer/ipmi/pollsters/sensor.py:68
#, python-format
msgid "Polling %(mtr)s sensor failed for %(cnt)s times!"
msgstr ""

#: ceilometer/network/floatingip.py:54
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr ""

#: ceilometer/network/services/fwaas.py:48
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:62
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:110
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:151
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:256
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr ""

#: ceilometer/network/services/vpnaas.py:49
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:58
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/unit/network/statistics/opendaylight/test_client.py:146
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:169
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/rgw_client.py:48
#, python-format
msgid "RGW AdminOps API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/messaging.py:104
#, python-format
msgid "Publishing policy set to %s"
msgstr ""

#: ceilometer/publisher/messaging.py:106
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/messaging.py:159
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/messaging.py:171
#, python-format
msgid "Failed to publish %d datapoints, queue them"
msgstr ""

#: ceilometer/publisher/messaging.py:175
#, python-format
msgid "Failed to publish %d datapoints, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:67
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/impl_log.py:41
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr ""

#: ceilometer/storage/impl_log.py:53
#, python-format
msgid "Dropping metering data with TTL %d"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:307
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:364
#, python-format
msgid "%d samples removed from database"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:400
msgid "Expired residual resource and meter definition data"
msgstr ""

#: ceilometer/storage/hbase/utils.py:474
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr ""

#: ceilometer/storage/mongo/utils.py:264
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: ceilometer/storage/mongo/utils.py:279
#, python-format
msgid "Unable to connect to the database server: %(errmsg)s."
msgstr ""

#: ceilometer/storage/mongo/utils.py:418
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb after %(retries)d retries. "
"Giving up."
msgstr ""

#: ceilometer/storage/mongo/utils.py:422
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

#: ceilometer/storage/mongo/utils.py:469
#, python-format
msgid "Index %s will be recreate."
msgstr ""

#: ceilometer/transformer/arithmetic.py:57
#, python-format
msgid "Arithmetic transformer must use at least one meter in expression '%s'"
msgstr ""

#: ceilometer/transformer/arithmetic.py:79
msgid "Expression evaluated to a NaN value!"
msgstr ""

#: ceilometer/transformer/arithmetic.py:95
#, python-format
msgid "Unable to evaluate expression %(expr)s: %(exc)s"
msgstr ""

#: ceilometer/transformer/conversions.py:199
#, python-format
msgid "dropping out of time order sample: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:217
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

