# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-09-09 06:08+0000\n"
"PO-Revision-Date: 2014-09-02 00:36+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Spanish (http://www.transifex.com/projects/p/ceilometer/"
"language/es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: ceilometer/collector.py:132
msgid "Dispatcher failed to handle the sample, requeue it."
msgstr ""

#: ceilometer/coordination.py:76
msgid "Error connecting to coordination backend."
msgstr ""

#: ceilometer/coordination.py:89
msgid "Error sending a heartbeat to coordination backend."
msgstr ""

#: ceilometer/coordination.py:142
msgid "Error getting group membership info from coordination backend."
msgstr ""

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Se está descartando excepción original: %s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "La excepción inesperada ha ocurrido %d vez(veces)... reintentando."

#: ceilometer/openstack/common/lockutils.py:117
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "No se ha podido liberar el bloqueo adquirido `%s`"

#: ceilometer/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "en llamada en bucle de duración fija"

#: ceilometer/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "en llamada en bucle dinámica"

#: ceilometer/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "Ha ocurrido un error al interpretar la regla %s"

#: ceilometer/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "No hay manejador para coincidencias de clase %s"

#: ceilometer/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "Ha ocurrido un error al interpretar la regla %r"

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Excepción durante limpieza de rpc."

#: ceilometer/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Excepción no controlada"
