# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-19 06:01+0000\n"
"PO-Revision-Date: 2014-06-18 08:06+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/ceilometer/"
"language/ja/)\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ceilometer/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "除去される元の例外: %s"

#: ceilometer/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "予期せぬ例外が、%d回()発生しました。再試行中。"

#: ceilometer/openstack/common/lockutils.py:120
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr "取得したロック `%s` を解放できませんでした"

#: ceilometer/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr "一定期間の呼び出しループ"

#: ceilometer/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr "動的呼び出しループ"

#: ceilometer/openstack/common/policy.py:510
#, python-format
msgid "Failed to understand rule %s"
msgstr "ルール %s を解釈できませんでした"

#: ceilometer/openstack/common/policy.py:520
#, python-format
msgid "No handler for matches of kind %s"
msgstr "種類 %s の一致向けのハンドラーがありません"

#: ceilometer/openstack/common/policy.py:790
#, python-format
msgid "Failed to understand rule %r"
msgstr "ルール %r を解釈できませんでした"

#: ceilometer/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "RPCクリーンアップ中に例外が発生"

#: ceilometer/openstack/common/service.py:276
msgid "Unhandled exception"
msgstr "未処理例外"

#: ceilometer/openstack/common/db/api.py:72
msgid "DB exceeded retry limit."
msgstr "DBへのリトライが上限に達しました。"

#: ceilometer/openstack/common/db/api.py:76
msgid "DB connection error."
msgstr "DB接続エラーが発生しました。"

#: ceilometer/openstack/common/db/sqlalchemy/session.py:460
msgid "DB exception wrapped."
msgstr "DB 例外がラップされました。"

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:267
#, python-format
msgid "Failed to migrate to version %s on engine %s"
msgstr "バージョン%sをエンジン%sへの移行が失敗しました。"

#: ceilometer/openstack/common/middleware/catch_errors.py:40
#, python-format
msgid "An error occurred during processing the request: %s"
msgstr ""
